name: Example

on:
  push:
    branches: [ 'master' ]
  workflow_dispatch:

jobs:
  full-build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: ActiveEngagement/theguru@feature-33
        with:
          user_email: ${{ secrets.GURU_USER_EMAIL }}
          user_token: ${{ secrets.GURU_USER_TOKEN }}
          collection_id: 68517b36-e873-4bf0-8aae-c486ea45ea0d
          board_id: ipjEjX5T/Test
          board_section_id: b42cb5c9-29f9-44ac-8664-2f0711b68b6d
          cards: |
            {
              "doc/test.md": "Test Card"
            }
