name: Example

on:
  push:
    branches: [ master ]

jobs:
  full-build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: ActiveEngagement/deployer-action@master
        with:
          examples: |
            {
              "public/build": "build"
            }
