name: Example

on:
  push:
    branches: [ master ]

jobs:
  full-build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: ActiveEngagement/deployer-action@manifest
        with:
          ssh_host: forge@staging.doalchemy.com
          ssh_key: ${{ secrets.KEY }}
          destination: test-bundles
          artifacts: |
            {
              "build": "public/build"
            }
