name: Example

on:
  push:
    branches: [ master ]

jobs:
  full-build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: ActiveEngagement/deployer-action@master
        with:
          ssh_key: ${{ secrets.KEY }}
          server_dir: .deploy-artifacts/staging.doalchemy.com/build
          artifacts: |
            {
              "build": "public/build"
            }
