name: Example

on:
  push:
    branches: [ 'master' ]

jobs:
  full-build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: ActiveEngagement/theguru@master
        with:
          user_email: ${{ secrets.GURU_USER_EMAIL }}
          user_token: ${{ secrets.GURU_USER_TOKEN }}
          doc_path: './doc'
          collection_id: '68517b36-e873-4bf0-8aae-c486ea45ea0d'
          board_id: 'dea1f633-601a-4fb3-82e8-8e3ecf1d9931'

