name: Example

on:
  push:
    branches: [ master ]

jobs:
  full-build:

    runs-on: ubuntu-latest
    
    steps:
      - name: Setup upterm session
        uses: lhotari/action-upterm@v1
      - uses: ActiveEngagement/deployer-action@master
        with:
          artifacts: |
            {
              "build": "public/build"
            }
