name: Example

on:
  push:
    branches: [ master ]

jobs:
  full-build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: ActiveEngagement/deployer-action@master
        with:
          example: |
            one: 1
            two: 2
            three: 3
