name: Example

on:
  push:
    tags: [ 'v*' ]

jobs:
  full-build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - uses: ActiveEngagement/deployer-action@master
        with:
          ssh_host: forge@staging.doalchemy.com
          ssh_key: ${{ secrets.KEY }}
          destination: test-bundles
          artifacts: |
            {
              "build": "public/build"
            }
          env: testing
          version: ${{ github.ref_name }}
